### ISSUE TITLE
挂梯无法登陆？

### ISSUE THREAD

**Issue by Smile8848** [niuhuan/jenny#1]
![UAY) (_8PDHN5~ON2RM30T5](https://user-images.githubusercontent.com/31927778/216807322-60a70dc6-9fab-409b-acd6-e442eceb7039.jpg)

**Comment by Smile8848** [comment]
不挂梯能正常使用。。。最近怎么老碰到这种。。

**Comment by niuhuan** [comment]
> 不挂梯能正常使用。。。最近怎么老碰到这种。。

不挂梯。或者换分流试试。这个只是第三方app，官方应用也是这样。

**Comment by Smile8848** [comment]
> > 不挂梯能正常使用。。。最近怎么老碰到这种。。
> 
> 不挂梯。或者换分流试试。这个只是第三方app，官方应用也是这样。

网页可以正常访问，挂梯不行。

**Comment by niuhuan** [comment]
> > > 不挂梯能正常使用。。。最近怎么老碰到这种。。
> > 
> > 
> > 不挂梯。或者换分流试试。这个只是第三方app，官方应用也是这样。
> 
> 网页可以正常访问，挂梯不行。

这个软件是用官方app协议，而不是官方网页协议。我觉得官方的app也挺简陋的。
