### ISSUE TITLE
webdav同步功能反馈

### ISSUE THREAD

**Issue by Ren9527** [niuhuan/jenny#10]
每次更换版本，使用同步功能，都会默认执行上传备份，将云端进度覆盖，导致恢复失败。
        建议采用阅读app的同步方式，手动进行的备份和从云端恢复分开处理。

**Comment by niuhuan** [comment]
WebDav同步是一种合并操作，先下载再上传。自动同步每次打开app的时候。webdav服务并不稳定，云端文件出错，才会删除服务器上的文件。

**Comment by RealKiro** [comment]
坚果云同步失败，提示403

**Comment by niuhuan** [comment]
> 坚果云同步失败，提示403

403是设置的不对，可以去群里问正在用webdav的群友。
