### ISSUE TITLE
下载后无法导出

### ISSUE THREAD

**Issue by eternityruraro** [niuhuan/jenny#12]
下载后无法导出

**Comment by niuhuan** [comment]
描述过于简单

**Comment by eternityruraro** [comment]
点击下载导出界面，可以勾选已下载的漫画，但没有可以下一步操作的按键或功能

**Comment by willait** [comment]
> 点击下载导出界面，可以勾选已下载的漫画，但没有可以下一步操作的按键或功能

有的，只是作者字体的颜色没调好，软件用白色主题的话，右上角的选项看不到，你把软件主题换成深色模式，就看到了。
另外希望作者以后可以改改。

**Comment by niuhuan** [comment]
> > 点击下载导出界面，可以勾选已下载的漫画，但没有可以下一步操作的按键或功能
> 
> 有的，只是作者字体的颜色没调好，软件用白色主题的话，右上角的选项看不到，你把软件主题换成深色模式，就看到了。 另外希望作者以后可以改改。

您用的并不是最新版吧？

**Comment by niuhuan** [comment]
颜色的问题是0.0.1-0.0.3之间修复的

**Comment by willait** [comment]
> > > 点击下载导出界面，可以勾选已下载的漫画，但没有可以下一步操作的按键或功能
> > 
> > 
> > 有的，只是作者字体的颜色没调好，软件用白色主题的话，右上角的选项看不到，你把软件主题换成深色模式，就看到了。 另外希望作者以后可以改改。
> 
> 您用的并不是最新版吧？

我用的就是最新的0.0.4，我刚又卸载重新安装了下，还是颜色有问题啊…奇怪

**Comment by niuhuan** [comment]
> > > > 点击下载导出界面，可以勾选已下载的漫画，但没有可以下一步操作的按键或功能
> > > 
> > > 
> > > 有的，只是作者字体的颜色没调好，软件用白色主题的话，右上角的选项看不到，你把软件主题换成深色模式，就看到了。 另外希望作者以后可以改改。
> > 
> > 
> > 您用的并不是最新版吧？
> 
> 我用的就是最新的0.0.4，我刚又卸载重新安装了下，还是颜色有问题啊…奇怪

我应该是没有调节导出列表界面的颜色。

**Comment by willait** [comment]
> > > > > 点击下载导出界面，可以勾选已下载的漫画，但没有可以下一步操作的按键或功能
> > > > 
> > > > 
> > > > 有的，只是作者字体的颜色没调好，软件用白色主题的话，右上角的选项看不到，你把软件主题换成深色模式，就看到了。 另外希望作者以后可以改改。
> > > 
> > > 
> > > 您用的并不是最新版吧？
> > 
> > 
> > 我用的就是最新的0.0.4，我刚又卸载重新安装了下，还是颜色有问题啊…奇怪
> 
> 我应该是没有调节导出列表界面的颜色。0.0.5修复一下

额，对的。之前是我表述的不够具体，到您截图这里是正常的，之后的下一步在导出列表中选中需导出的内容时，右上角的“全选”、“确认”在亮色下看不到。
