### ISSUE TITLE
批量导出

### ISSUE THREAD

**Issue by yaBorn** [niuhuan/jenny#15]
需要全部导出时，已有部分项目成功导出，但中途某项目导出失败，导出结束。
删掉下载列表中导出失败的该项目，重新全部导出。
只能去文件夹中删掉已经导出的文件，从第一个项目重新导出（否则要自己选择未导出项目）。
浪费很多重复导出的时间。

建议导出时增加选项，“导出成功删除该项目”。
已导出的项目从下载列表中删除，减少重复导出。

**Comment by niuhuan** [comment]
我觉得可以增加导出后删除的选项
