### ISSUE TITLE
取消收藏之后收藏夹仍然存在收藏项的bug

### ISSUE THREAD

**Issue by mx41shy** [niuhuan/jenny#19]
目前版本收藏夹取消收藏项目之后无法刷新，收藏项目一直存在，关闭软件后/退出收藏后再进入收藏夹仍然存在被取消收藏的项目，过一天才会消失。

**Comment by niuhuan** [comment]
好的👌可能是缓存问题。你也可以试试收藏新东西会不会消失

**Comment by niuhuan** [comment]
今天测试了一下,官方的接口就这样 😨

**Comment by mx41shy** [comment]
> 今天测试了一下,官方的接口就这样 😨

那是否可以读取项目的收藏状态，如果未收藏的话作隐藏处理呢？

**Comment by niuhuan** [comment]
如果挨个读取一遍还是挺慢的，会请求太多次

**Comment by 1401341324** [comment]
这个问题有一个逆天的解决方案，翻页调最后一页的接口，然后再获取首页，就能得到最新的收藏夹

**Comment by mx41shy** [comment]
> 今天测试了一下,官方的接口就这样 😨

今天测试了一下，官方的App确实取消收藏之后不会消失，但是官方的网页取消收藏之后就不再显示收藏了
