### ISSUE TITLE
不愧是你，但是感觉密码输入框的逻辑设计有点奇怪

### ISSUE THREAD

**Issue by Minori-ty** [niuhuan/jenny#2]
就是本来显示了输入框，直接输入就行了。但是聚焦后，还会弹出一个输入框进行输入，就感觉有点奇怪和画蛇添足的感觉。另一个也是

**Comment by lsnsb** [comment]
兄弟怎么注册我不会能教我一下吗

**Comment by Minori-ty** [comment]
> 兄弟怎么注册我不会能教我一下吗
> 

去禁漫官网注册

**Comment by lsnsb** [comment]
兄弟链接可以发我一下吗我真找不到。d谢谢

**Comment by Minori-ty** [comment]
> 兄弟链接可以发我一下吗我真找不到。d谢谢
> 

谷歌搜索禁漫天堂，第一个就是了
https://18comic.vip

**Comment by lsnsb** [comment]
感谢

**Comment by zsjlovezgf** [comment]
哥们这个软件怎么下😂😂麻烦教一下，谢谢

**Comment by Minori-ty** [comment]
> 哥们这个软件怎么下😂😂麻烦教一下，谢谢

https://github.com/niuhuan/jenny/releases
 
选择arm64

**Comment by zsjlovezgf** [comment]
好的好的，谢谢啦

**Comment by Minori-ty** [comment]
> 

你们真的不会翻墙吗？不会用vpn？怎么上的GitHub的？

**Comment by Minori-ty** [comment]
> 好像进不去啊

你们真的不会翻墙吗？不会用vpn？怎么上的GitHub的？

**Comment by 3287968489** [comment]
> > 好像进不去啊
> 
> 你们真的不会翻墙吗？不会用vpn？怎么上的GitHub的？

完全不会(／_＼)大怨种

**Comment by 3287968489** [comment]
> > 好像进不去啊
> 
> 你们真的不会翻墙吗？不会用vpn？怎么上的GitHub的？

怎么翻墙啊英雄

**Comment by zombie1912** [comment]
有什么好用VPN推荐一下

**Comment by zombie1912** [comment]
@Minori-ty 有什么好用VPN推荐一个

**Comment by Minori-ty** [comment]
> @Minori-ty 有什么好用VPN推荐一个

想要在 Facebook、Twitter 交外国好友？用这个梯子试试吧！

下载链接（推荐使用浏览器访问）：https://bitbucket.org/letsgogo/letsgogo_20/src/master/README.md

备用链接（推荐使用浏览器访问）：https://github.com/LetsGo666/LetsGo_4

安装后打开填写我的ID：62175103 你能多得3天会员！

**Comment by 1433020484** [comment]
请问之前wax打开密码多少有人知道嘛

**Comment by Minori-ty** [comment]
> 请问之前wax打开密码多少有人知道嘛

他仓库最新版那里写了个神秘代码，就是密码，你自己翻吧

**Comment by 1433020484** [comment]
> > 请问之前wax打开密码多少有人知道嘛
> 
> 他仓库最新版那里写了个神秘代码，就是密码，你自己翻吧

老哥，没找到，求助🥺

**Comment by Minori-ty** [comment]
> > > 请问之前wax打开密码多少有人知道嘛
> > 
> > 他仓库最新版那里写了个神秘代码，就是密码，你自己翻吧
> 
> 老哥，没找到，求助🥺

![Screenshot_2023-06-04-11-41-12-284_com.github.android-edit.jpg](https://github.com/niuhuan/jenny/assets/79521943/ab53a66e-09fe-46e8-ac46-b3c36e6ea181)

**Comment by 1433020484** [comment]
> > > > 请问之前wax打开密码多少有人知道嘛
> > > 
> > > 他仓库最新版那里写了个神秘代码，就是密码，你自己翻吧
> > 
> > 老哥，没找到，求助🥺
> 
> ![Screenshot_2023-06-04-11-41-12-284_com.github.android-edit.jpg](https://github.com/niuhuan/jenny/assets/79521943/ab53a66e-09fe-46e8-ac46-b3c36e6ea181)
> 
> 

老哥，这个没用我之前已经试过了😭
