### ISSUE TITLE
Monet取色

### ISSUE THREAD

**Issue by MarkChan0225** [niuhuan/jenny#20]
既然都美化版本了 不如再加一个monet取色吧

**Comment by niuhuan** [comment]
自定义Theme，有没有现成的app参考？

**Comment by MarkChan0225** [comment]
Monet取色 也称为Dynamic Color 是谷歌在安卓实12引入的颜色引擎 通过在用户的壁纸提取主题色 供使用的Monet取色提供主颜色

https://m3.material.io/styles/color/dynamic-color/overview

**Comment by niuhuan** [comment]
🤣 可以研究研究。只适配一下安卓也可以

**Comment by MarkChan0225** [comment]
https://pub.dev/packages/dynamic_color
刚刚找到了一个flutter库可以比较轻松地制作monet

**Comment by niuhuan** [comment]
好的, 我做的时候会参考一下, 不过请您不要着急, 我会在空档尝试, 我现在不能保证多久能做出来。

**Comment by MarkChan0225** [comment]
没事 我真的不急 我明白业余开发者的 我只是想降低开发难度

**Comment by niuhuan** [comment]
软件都快死了, 暂时先关了这个issue
