### ISSUE TITLE
发电成功但又没完全成功

### ISSUE THREAD

**Issue by DODOTAX** [niuhuan/jenny#23]
Jenny 0.1.1
Telegram 上已签到，点击发电显示success ，但发电详情没有变化![Screenshot_2023-04-11-12-26-55-516_opensource.jenny.jpg](https://user-images.githubusercontent.com/89824742/231056692-aecbecb0-de26-424f-af91-6a3a024fcbfb.jpg)

**Comment by niuhuan** [comment]
你看见闪电图标下面那个用户名没, 去群里再绑定一下, 再签到一下, 再我成精发过电一下

**Comment by DODOTAX** [comment]
> 你看见闪电图标下面那个用户名没, 去群里再绑定一下, 再签到一下, 再我成精发过电一下

之前试过没用，刚才又试了一下，依然不行

**Comment by niuhuan** [comment]
在TG联系吧, 看起来比较麻烦。

**Comment by w20050817** [comment]
加载不出来群聊

**Comment by niuhuan** [comment]
我觉得是输入了不一致的用户名导致的

**Comment by niuhuan** [comment]
> 还是加载不出来

挂个梯子
