### ISSUE TITLE
怎么注册账号啊

### ISSUE THREAD

**Issue by 3287968489** [niuhuan/jenny#26]

**Comment by niuhuan** [comment]
Releases 页面有详细说明。如果您看不懂简体中文可以借助谷歌翻译 https://translate.google.com

**Comment by 3287968489** [comment]
> 助

浏览器点不进去啊

**Comment by niuhuan** [comment]
> > 助
> 
> 浏览器点不进去啊

必须使用港澳台或大陆IP，否则提示没有权限。

**Comment by 3287968489** [comment]
> > > 助
> > 
> > 浏览器点不进去啊
> 
> 必须使用港澳台或大陆IP，否则提示没有权限。

手机是不是不行啊

**Comment by niuhuan** [comment]
手机也可以
