### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 1401341324** [niuhuan/jenny#33]
下载漫画后导出时，如果原漫画名过长会导致导出的文件名过长从而导出失败

**Comment by niuhuan** [comment]
这是操作系统的限制，每个系统可允许长度都不一样。不过可以在设置里找找有没有导出时候重命名的功能。

**Comment by 1401341324** [comment]
软件内没看到相关功能 或许可以支持修改漫画名或文件名

**Comment by niuhuan** [comment]
功能在设置中
