### ISSUE TITLE
禁漫天堂继续阅读

### ISSUE THREAD

**Issue by mike2682077** [niuhuan/jenny#35]
在电脑端下载的漫画，导入到手机中，观看后退出，下次再进入。无法继续阅读，必须重头再来
那个bk就不会，退出后下次观看会接着上次继续
请大佬有空看看

**Comment by niuhuan** [comment]
试试用webdav同步阅读记录？

**Comment by mike2682077** [comment]
大佬，用了坚果云一直报错…是该用哪个？？

**Comment by mike2682077** [comment]
可以了，没新建文件夹…感谢大佬
