### ISSUE TITLE
打开APP出现问题

### ISSUE THREAD

**Issue by lpzju** [niuhuan/jenny#36]
arm32和arm64安装之后，打开就是计算器界面
![image](https://github.com/niuhuan/jenny/assets/87311013/d259434b-96c8-4860-80e9-c0345bb6fd86)
x86暗装不了
以上在开启VPN和无VPN情况下都是如此
系统是MIUI14.0.3，应该是Android13

**Comment by niuhuan** [comment]
下载界面里有提示

**Comment by lpzju** [comment]
> 下载界面里有提示

没有明白这句话
又看了一下，好像也没有不兼容说明
请教一下有什么解决办法嘛~

**Comment by niuhuan** [comment]
下载界面不是有密码么？

**Comment by lpzju** [comment]
> 下载界面不是有密码么？

谢谢谢谢，解决力
