### ISSUE TITLE
jenny 的网络线路只有二还活着

### ISSUE THREAD

**Issue by shuisyf** [niuhuan/jenny#45]
jenny 的网络线路只有二还活着

**Comment by w57kt8** [comment]
![Screenshot_20231006_140653](https://github.com/niuhuan/jenny/assets/147130454/f9188431-a886-4e37-a12c-180b0f01c3ed)

**Comment by w57kt8** [comment]
你好，能告诉我怎么登录吗，需要账号密码，但我不会弄
