### ISSUE TITLE
更新之后一直显示被玩坏了，登录也显示失败

### ISSUE THREAD

**Issue by JKKJ9204** [niuhuan/jenny#49]
![Screenshot_2023-10-26-22-23-10-19_d9c1fb969fd432e](https://github.com/niuhuan/jenny/assets/119020178/0ca16e92-5b94-4c17-9a9c-42fa41875240)
![Screenshot_2023-10-26-22-24-20-91_d9c1fb969fd432e](https://github.com/niuhuan/jenny/assets/119020178/31061dd9-71e1-43c9-bf7e-e9c4f8a7441a)

**Comment by 563012289** [comment]
同样的，有没有解决办法

**Comment by 7sir** [comment]
＋1

**Comment by AnTian1** [comment]
我也是

**Comment by niuhuan** [comment]
确认是最新版，然后用右上角的菜单切换分流
