### ISSUE TITLE
jenny怎么回事，看不了了，

### ISSUE THREAD

**Issue by 18143418696** [niuhuan/jenny#52]
jenny怎么回事，看不了了，作者能给了解释一下吗，以后都用不了?

**Comment by niuhuan** [comment]
我为什么要解释，我不服…… 哭了

**Comment by 18143418696** [comment]
> 我为什么要解释，我不服…… 哭了
APP怎么回事啊，用不了了，你作者也不说句话

**Comment by niuhuan** [comment]
能修复就看，修复不了用pikapika

**Comment by niuhuan** [comment]
修复APP需要时间，不会一下子就好嘛

**Comment by 18143418696** [comment]
> 能修复就看，修复不了用pikapika

好吧

**Comment by 18143418696** [comment]
> 修复APP需要时间，不会一下子就好嘛

谢谢老板，这个APP很好用，

**Comment by itahi02** [comment]
打开是计算器是什么原因？

**Comment by kirto123** [comment]
> 修复APP需要时间，不会一下子就好嘛

大佬，1.01以上的版本打开都是计算器怎么搞啊

**Comment by axiang57124** [comment]
app很好用  我愿意等作者修复并赞助他

**Comment by ZDRRRRRR** [comment]
> 我为什么要解释，我不服…… 哭了

大佬，计算器密码是多少，现在界面没有密码了

**Comment by zzh19879610798** [comment]
> > 我为什么要解释，我不服…… 哭了
> 
> 大佬，计算器密码是多少，现在界面没有密码了

5686648=
