### ISSUE TITLE
软件打开变成计算器

### ISSUE THREAD

**Issue by kirto123** [niuhuan/jenny#53]
从1.01往上的版本，打开都会变成计算器，什么原因啊，现在1.01也用不了了

**Comment by nevereverdhdh** [comment]
好像是要6位密码，我也在找

**Comment by RAYkrain** [comment]
密码说是在下载页面，我找了半天也没找到啊

**Comment by zzh19879610798** [comment]
> 从1.01往上的版本，打开都会变成计算器，什么原因啊，现在1.01也用不了了

5686648=

**Comment by zzh19879610798** [comment]
> 好像是要6位密码，我也在找

5686648=

**Comment by zzh19879610798** [comment]
> 密码说是在下载页面，我找了半天也没找到啊

5686648=
