### ISSUE TITLE
登录不了

### ISSUE THREAD

**Issue by 2273149557** [niuhuan/jenny#55]
![Screenshot_20231026_151527](https://github.com/niuhuan/jenny/assets/128462636/dcc8b4e4-2e86-4990-ad13-7525467d4edc)

**Comment by yaosu1994** [comment]
计算器的密令是多少？

**Comment by 2273149557** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "niuhuan/jenny"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月27日(星期五) 晚上11:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [niuhuan/jenny] 登录不了 (Issue #55)





 
计算器的密令是多少？

**Comment by xvgdjaj** [comment]
不是登录计算机的密码是啥忘记了，怎么本子全是jm娘了

**Comment by 2273149557** [comment]
以前要是进去就是5686648
现在是直接要登录账号，然后就
Bad state:.:expected value
at line 1 column 1
通俗易懂的就是，现在直接点APP就直接要输入账号和密码，输入过后就
Bad state:.:expected value
at line 1 column 1

**Comment by niuhuan** [comment]
旧版本已经不能正常登录了, 官方接口已经变动了

**Comment by 2273149557** [comment]
观看每个本子是为什么都是广告，没有内容

**Comment by 2273149557** [comment]
都是AG
