### ISSUE TITLE
密码说是在下载页面 但我找了半天也没找到是不是我进错了？

### ISSUE THREAD

**Issue by RAYkrain** [niuhuan/jenny#59]
![Screenshot_2023-10-28-15-33-24-73_439a3fec0400f8974d35eed09a31f914](https://github.com/niuhuan/jenny/assets/149229600/35864861-8922-466c-83fb-2ee679eb9f6d)
![Uploading Screenshot_2023-10-28-15-33-19-33_439a3fec0400f8974d35eed09a31f914.jpg…]()

**Comment by kirto123** [comment]
俺也一样，根本找不到密码

**Comment by 2318284570** [comment]
都是之前还有的

**Comment by lwc2003** [comment]
谁知道计算机密码多少啊

**Comment by zzh19879610798** [comment]
> 谁知道计算机密码多少啊

5686648=

**Comment by zzh19879610798** [comment]
> 谁知道计算机密码多少啊

5686648=

**Comment by zzh19879610798** [comment]
> 俺也一样，根本找不到密码

5686648=

**Comment by zzh19879610798** [comment]
5686648=
