### ISSUE TITLE
登录

### ISSUE THREAD

**Issue by 1428466811** [niuhuan/jenny#60]
不是计算器登录方式倒是标注一下啊，是有偿还是有群至少回复一下吧，这么多人问一个都不回是什么情况啊

**Comment by 1428466811** [comment]
5686648=

**Comment by zzh19879610798** [comment]
> 5686648=

你咋知道的哥，给个渠道

**Comment by 1428466811** [comment]
> > 5686648=
> 
> 你咋知道的哥，给个渠道

贴吧找到的，不懂为什么作者不给标注

**Comment by niuhuan** [comment]
以前是有标注的，现在已经不能用了，全变jm娘了，下载入口也隐藏了。
