### ISSUE TITLE
自从0.16版本开始就一直安装失败

### ISSUE THREAD

**Issue by LeeZimo** [niuhuan/jenny#61]
安装显示设备未安装AppSync，实际上越狱后其他所有IPA都是正常的，0.14版本也是正常的。但是自0.16版本之后都无法正常安装。请问是我的cydia里补丁版本过低了吗？如果过低请问在哪里可以下载新的补丁，拜托大佬给个好资源站点

**Comment by zzh19879610798** [comment]
计算机上的密码是多少

**Comment by niuhuan** [comment]
ios版本会不会低了
