### ISSUE TITLE
为什么加载不出来啊，账号那边页面显示检查网络或代理设置，可是我网络没有问题啊？

### ISSUE THREAD

**Issue by 2144646744** [niuhuan/jenny#63]

**Comment by 2144646744** [comment]
![Screenshot_2023-10-29-20-00-09-07_d9c1fb969fd432ed8cf61c4875620998.jpg](https://github.com/niuhuan/jenny/assets/131507438/19dba008-043f-4527-b1d0-2767efc995c8)

**Comment by 2144646744** [comment]
![Screenshot_2023-10-29-20-00-05-30_d9c1fb969fd432ed8cf61c4875620998.jpg](https://github.com/niuhuan/jenny/assets/131507438/ffbfbfb2-7a37-43db-a8e5-2f1273765eaf)

**Comment by 2144646744** [comment]
就是这两张图，网络没有问题，挂了梯子也不行

**Comment by niuhuan** [comment]
不挂梯子换分流试试
