### ISSUE TITLE
网络一直不行


### ISSUE THREAD

**Issue by 1073920061** [niuhuan/jenny#67]

**Comment by Minori-ty** [comment]
为什么网络老是会出现问题，是禁漫那边一直在改吗？可以做成在线更新api吗？这样就不用老是更新app了  @niuhuan

**Comment by niuhuan** [comment]
我觉得我不行了，每次改好一会儿就被封了

**Comment by niuhuan** [comment]
不知道行不行，flutter静态编译 ， 热更新难搞

**Comment by Minori-ty** [comment]
> 我觉得我不行了，每次改好一会儿就被封了

可以把api做成你的GitHub仓库，然后app在网络请求失败的时候，触发fetch，获取你GitHub新的api，然后替换app本地localStroge的api。
在网络失败的时候，你只需要更新一下仓库的api就行了，就不用每次打包新的app了。

**Comment by Minori-ty** [comment]
> 不知道行不行，flutter静态编译 ， 热更新难搞

辛苦了。不说了，我这就给您赞助去了

**Comment by niuhuan** [comment]
不用不用，不知道能不能坚持多久

**Comment by niuhuan** [comment]
jenny感觉快寿终正寝了

**Comment by axiang57124** [comment]
软件这么好用哎

**Comment by wdq0105** [comment]
那个密码是什么意思？哪位大神帮忙解释一下

**Comment by Minori-ty** [comment]
> 那个密码是什么意思？哪位大神帮忙解释一下

密码就是，你下载这个软件的时候，初始化是伪装成一个计算器，你按照给的密码按，就能进入真正的页面。不过这个软件不能用了

**Comment by yzxjoe** [comment]
啊？咋回事啊？为什么我的还能用

**Comment by hwljdbao** [comment]
感觉快不行了
